### PR TITLE
Modelcar

### PR DESCRIPTION
**Pull request by strangiato**
This updates the vllm instance to the latest version of vllm from 2.14 (vllm v0.5.5).

It also updates the deployment to utilize modelcar to deploy the model.

### CODE REVIEW

**Comment by strangiato** [comment]
@Jaland This one may be worth talking about over a quick call.

One of the important things that this changes is that I did update the `'--served-model-name={{ .Name }}'` to match what the RHOAI team is doing in the current vLLM template instead of us setting the model-name from the values file.

The `{{ .Name }}` is using the K8s downward API to pull the object name which currently is `vllm`.  We may want to update that to something more meaningful:

Screenshot 2024-11-05 at 5 03 58 PM

I'm not sure what the implications of this change are on the llm-router side since this changes the model name which will impact the API requests.  I'm also not sure if this has any impact to some of the info that gets filtered up through the UI in composer.

**Comment by Jaland** [comment]
Okay yeah I'm back tomorrow so let's do a quick sync just so that I make sure I understand all of the changes in the implications. 

But overall it this looks like a solid update, most of those pieces were just left over from an earlier draft of this and haven't really been updated. 

As far as changing how the model name looks, that should be okay. I think that'll just end up being a property/env change we need to make inside the quarkus app to get it to work.

**Comment by strangiato** [comment]
I'm removing the follow params in the servingruntime:

```
        - --max-model-len
        - "{{ .Values.runtime.maxModelLength }}"
        - --gpu-memory-utilization
        - "{{ .Values.runtime.gpuMemoryUtilization }}"
        - --max-seq_len-to-capture
        - "{{ .Values.runtime.maxSeqLength }}"
```

According the vLLM documentation, `max-model-len` should get configured from the `config.json` file provided by the model if we don't explicitly set it.  

`max-seq_len-to-capture` should actually be `max-seq-len-to-capture` so that one isn't actually doing anything.  The value we are providing is the default value though so this one doesn't matter.

`gpu-memory-utilization` defaults to .9 and we are providing 1.  This one determines what percentage of the GPU memory we should be utilizing.  Using 1 is usually not recommended because it can cause memory errors and you want to leave a little bit of a buffer.

**Comment by strangiato** [comment]
Functional LLM chatbot!

Screenshot 2024-11-07 at 9 47 29 AM

**Pull request merged**
